"""add zero trust tables

Revision ID: 46a3f5e47265
Revises: 0ab65e1cc7fa
Create Date: 2025-07-04 00:07:28.021367

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a3f5e47265'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zero_trust_users',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='用户唯一标识'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱地址'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('salt', sa.String(length=255), nullable=False, comment='密码盐值'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='用户真实姓名'),
    sa.Column('department', sa.String(length=255), nullable=True, comment='部门'),
    sa.Column('role', sa.String(length=100), server_default='user', nullable=False, comment='用户角色'),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False, comment='用户状态'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录IP地址'),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='失败登录尝试次数'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='锁定截止时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='zero_trust_user_pkey'),
    sa.UniqueConstraint('email', name='unique_zero_trust_email'),
    sa.UniqueConstraint('username', name='unique_zero_trust_username')
    )
    with op.batch_alter_table('zero_trust_users', schema=None) as batch_op:
        batch_op.create_index('zero_trust_user_email_idx', ['email'], unique=False)
        batch_op.create_index('zero_trust_user_status_idx', ['status'], unique=False)
        batch_op.create_index('zero_trust_user_username_idx', ['username'], unique=False)

    op.create_table('zero_trust_audit_logs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='日志唯一标识'),
    sa.Column('user_id', models.types.StringUUID(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('resource', sa.String(length=255), nullable=True, comment='操作资源'),
    sa.Column('result', sa.String(length=50), nullable=False, comment='操作结果'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='客户端IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理信息'),
    sa.Column('details', sa.JSON(), nullable=True, comment='操作详细信息'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['zero_trust_users.id'], name='fk_zero_trust_audit_log_user_id'),
    sa.PrimaryKeyConstraint('id', name='zero_trust_audit_log_pkey')
    )
    with op.batch_alter_table('zero_trust_audit_logs', schema=None) as batch_op:
        batch_op.create_index('zero_trust_audit_log_action_idx', ['action'], unique=False)
        batch_op.create_index('zero_trust_audit_log_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('zero_trust_audit_log_ip_idx', ['ip_address'], unique=False)
        batch_op.create_index('zero_trust_audit_log_user_id_idx', ['user_id'], unique=False)

    op.create_table('zero_trust_tokens',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Token唯一标识'),
    sa.Column('user_id', models.types.StringUUID(), nullable=False, comment='关联的用户ID'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Token哈希值'),
    sa.Column('token_type', sa.String(length=50), server_default='access_token', nullable=False, comment='Token类型'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='颁发时间'),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False, comment='Token状态'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='撤销时间'),
    sa.Column('revoked_by', models.types.StringUUID(), nullable=True, comment='撤销操作者ID'),
    sa.Column('client_ip', sa.String(length=45), nullable=True, comment='客户端IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['zero_trust_users.id'], name='fk_zero_trust_token_user_id'),
    sa.PrimaryKeyConstraint('id', name='zero_trust_token_pkey'),
    sa.UniqueConstraint('token_hash', name='unique_zero_trust_token_hash')
    )
    with op.batch_alter_table('zero_trust_tokens', schema=None) as batch_op:
        batch_op.create_index('zero_trust_token_expires_idx', ['expires_at'], unique=False)
        batch_op.create_index('zero_trust_token_hash_idx', ['token_hash'], unique=False)
        batch_op.create_index('zero_trust_token_status_idx', ['status'], unique=False)
        batch_op.create_index('zero_trust_token_user_id_idx', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zero_trust_tokens', schema=None) as batch_op:
        batch_op.drop_index('zero_trust_token_user_id_idx')
        batch_op.drop_index('zero_trust_token_status_idx')
        batch_op.drop_index('zero_trust_token_hash_idx')
        batch_op.drop_index('zero_trust_token_expires_idx')

    op.drop_table('zero_trust_tokens')
    with op.batch_alter_table('zero_trust_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('zero_trust_audit_log_user_id_idx')
        batch_op.drop_index('zero_trust_audit_log_ip_idx')
        batch_op.drop_index('zero_trust_audit_log_created_at_idx')
        batch_op.drop_index('zero_trust_audit_log_action_idx')

    op.drop_table('zero_trust_audit_logs')
    with op.batch_alter_table('zero_trust_users', schema=None) as batch_op:
        batch_op.drop_index('zero_trust_user_username_idx')
        batch_op.drop_index('zero_trust_user_status_idx')
        batch_op.drop_index('zero_trust_user_email_idx')

    op.drop_table('zero_trust_users')
    # ### end Alembic commands ###
